# SITE CONFIGURATION
title: Music Rebl # your site title
author: AB # You :P
description: > # Meta description of Homepage
  Ultimate Tracklist Site Of A.R. Rahman
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
# social:
#   name: AB
#   links:
#     - https://twitter.com/ArunBharhath
#     - https://www.facebook.com/ArunBharhath

# THEME SETTINGS
navigation: # Navigation links
  # - {name: 'Home', link: '/'}
  # - {name: 'About', link: '/about'}
  # - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: musicrebl@protonmail.com # email for form submission

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: traklist/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
